
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}


//
//{"jwtToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE"}


###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE


###

GET http://localhost:3000/states/:stateId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE


###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE


Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###
GET http://localhost:3000/districts/:districtId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE


###

DELETE http://localhost:3000/districts/:districtId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE

###

PUT http://localhost:3000/districts/:districtId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE


Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/:stateId/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE



###

GET http://localhost:3000/districts/:districtId/details/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkxOTk0ODUyfQ.09HhWFygp8AAlfwzdURErl5GJmleubbRP-lrL0spsQE
